// Copyright 2026-present Orbit Contributors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.36.1
// source: orbit/plugin/v1/process_plugin.proto

package wire

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PluginHealth_Status int32

const (
	PluginHealth_STATUS_UNSPECIFIED PluginHealth_Status = 0
	PluginHealth_STATUS_HEALTHY     PluginHealth_Status = 1
	PluginHealth_STATUS_DEGRADED    PluginHealth_Status = 2
	PluginHealth_STATUS_UNHEALTHY   PluginHealth_Status = 3
)

// Enum value maps for PluginHealth_Status.
var (
	PluginHealth_Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STATUS_HEALTHY",
		2: "STATUS_DEGRADED",
		3: "STATUS_UNHEALTHY",
	}
	PluginHealth_Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"STATUS_HEALTHY":     1,
		"STATUS_DEGRADED":    2,
		"STATUS_UNHEALTHY":   3,
	}
)

func (x PluginHealth_Status) Enum() *PluginHealth_Status {
	p := new(PluginHealth_Status)
	*p = x
	return p
}

func (x PluginHealth_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PluginHealth_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_orbit_plugin_v1_process_plugin_proto_enumTypes[0].Descriptor()
}

func (PluginHealth_Status) Type() protoreflect.EnumType {
	return &file_orbit_plugin_v1_process_plugin_proto_enumTypes[0]
}

func (x PluginHealth_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PluginHealth_Status.Descriptor instead.
func (PluginHealth_Status) EnumDescriptor() ([]byte, []int) {
	return file_orbit_plugin_v1_process_plugin_proto_rawDescGZIP(), []int{5, 0}
}

type PluginCommand_Kind int32

const (
	PluginCommand_KIND_UNSPECIFIED PluginCommand_Kind = 0
	PluginCommand_KIND_ACTIVATE    PluginCommand_Kind = 1
	PluginCommand_KIND_DEACTIVATE  PluginCommand_Kind = 2
)

// Enum value maps for PluginCommand_Kind.
var (
	PluginCommand_Kind_name = map[int32]string{
		0: "KIND_UNSPECIFIED",
		1: "KIND_ACTIVATE",
		2: "KIND_DEACTIVATE",
	}
	PluginCommand_Kind_value = map[string]int32{
		"KIND_UNSPECIFIED": 0,
		"KIND_ACTIVATE":    1,
		"KIND_DEACTIVATE":  2,
	}
)

func (x PluginCommand_Kind) Enum() *PluginCommand_Kind {
	p := new(PluginCommand_Kind)
	*p = x
	return p
}

func (x PluginCommand_Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PluginCommand_Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_orbit_plugin_v1_process_plugin_proto_enumTypes[1].Descriptor()
}

func (PluginCommand_Kind) Type() protoreflect.EnumType {
	return &file_orbit_plugin_v1_process_plugin_proto_enumTypes[1]
}

func (x PluginCommand_Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PluginCommand_Kind.Descriptor instead.
func (PluginCommand_Kind) EnumDescriptor() ([]byte, []int) {
	return file_orbit_plugin_v1_process_plugin_proto_rawDescGZIP(), []int{7, 0}
}

type PluginMetadata struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Id                   string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Version              string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	ApiVersion           string                 `protobuf:"bytes,4,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	Dependencies         []string               `protobuf:"bytes,5,rep,name=dependencies,proto3" json:"dependencies,omitempty"`
	OptionalDependencies []string               `protobuf:"bytes,6,rep,name=optional_dependencies,json=optionalDependencies,proto3" json:"optional_dependencies,omitempty"`
	Capabilities         []string               `protobuf:"bytes,7,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	RequiredCapabilities []string               `protobuf:"bytes,8,rep,name=required_capabilities,json=requiredCapabilities,proto3" json:"required_capabilities,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *PluginMetadata) Reset() {
	*x = PluginMetadata{}
	mi := &file_orbit_plugin_v1_process_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginMetadata) ProtoMessage() {}

func (x *PluginMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_orbit_plugin_v1_process_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginMetadata.ProtoReflect.Descriptor instead.
func (*PluginMetadata) Descriptor() ([]byte, []int) {
	return file_orbit_plugin_v1_process_plugin_proto_rawDescGZIP(), []int{0}
}

func (x *PluginMetadata) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PluginMetadata) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PluginMetadata) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PluginMetadata) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *PluginMetadata) GetDependencies() []string {
	if x != nil {
		return x.Dependencies
	}
	return nil
}

func (x *PluginMetadata) GetOptionalDependencies() []string {
	if x != nil {
		return x.OptionalDependencies
	}
	return nil
}

func (x *PluginMetadata) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *PluginMetadata) GetRequiredCapabilities() []string {
	if x != nil {
		return x.RequiredCapabilities
	}
	return nil
}

type PluginFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*PluginFrame_Hello
	//	*PluginFrame_CommandResult
	//	*PluginFrame_Health
	//	*PluginFrame_CapabilityResult
	Payload       isPluginFrame_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginFrame) Reset() {
	*x = PluginFrame{}
	mi := &file_orbit_plugin_v1_process_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginFrame) ProtoMessage() {}

func (x *PluginFrame) ProtoReflect() protoreflect.Message {
	mi := &file_orbit_plugin_v1_process_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginFrame.ProtoReflect.Descriptor instead.
func (*PluginFrame) Descriptor() ([]byte, []int) {
	return file_orbit_plugin_v1_process_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *PluginFrame) GetPayload() isPluginFrame_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *PluginFrame) GetHello() *PluginHello {
	if x != nil {
		if x, ok := x.Payload.(*PluginFrame_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *PluginFrame) GetCommandResult() *CommandResult {
	if x != nil {
		if x, ok := x.Payload.(*PluginFrame_CommandResult); ok {
			return x.CommandResult
		}
	}
	return nil
}

func (x *PluginFrame) GetHealth() *PluginHealth {
	if x != nil {
		if x, ok := x.Payload.(*PluginFrame_Health); ok {
			return x.Health
		}
	}
	return nil
}

func (x *PluginFrame) GetCapabilityResult() *CapabilityResult {
	if x != nil {
		if x, ok := x.Payload.(*PluginFrame_CapabilityResult); ok {
			return x.CapabilityResult
		}
	}
	return nil
}

type isPluginFrame_Payload interface {
	isPluginFrame_Payload()
}

type PluginFrame_Hello struct {
	Hello *PluginHello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type PluginFrame_CommandResult struct {
	CommandResult *CommandResult `protobuf:"bytes,2,opt,name=command_result,json=commandResult,proto3,oneof"`
}

type PluginFrame_Health struct {
	Health *PluginHealth `protobuf:"bytes,3,opt,name=health,proto3,oneof"`
}

type PluginFrame_CapabilityResult struct {
	CapabilityResult *CapabilityResult `protobuf:"bytes,4,opt,name=capability_result,json=capabilityResult,proto3,oneof"`
}

func (*PluginFrame_Hello) isPluginFrame_Payload() {}

func (*PluginFrame_CommandResult) isPluginFrame_Payload() {}

func (*PluginFrame_Health) isPluginFrame_Payload() {}

func (*PluginFrame_CapabilityResult) isPluginFrame_Payload() {}

type PluginHello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProtocolMajor uint32                 `protobuf:"varint,1,opt,name=protocol_major,json=protocolMajor,proto3" json:"protocol_major,omitempty"`
	ProtocolMinor uint32                 `protobuf:"varint,2,opt,name=protocol_minor,json=protocolMinor,proto3" json:"protocol_minor,omitempty"`
	Metadata      *PluginMetadata        `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginHello) Reset() {
	*x = PluginHello{}
	mi := &file_orbit_plugin_v1_process_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginHello) ProtoMessage() {}

func (x *PluginHello) ProtoReflect() protoreflect.Message {
	mi := &file_orbit_plugin_v1_process_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginHello.ProtoReflect.Descriptor instead.
func (*PluginHello) Descriptor() ([]byte, []int) {
	return file_orbit_plugin_v1_process_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *PluginHello) GetProtocolMajor() uint32 {
	if x != nil {
		return x.ProtocolMajor
	}
	return 0
}

func (x *PluginHello) GetProtocolMinor() uint32 {
	if x != nil {
		return x.ProtocolMinor
	}
	return 0
}

func (x *PluginHello) GetMetadata() *PluginMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type CommandResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     uint64                 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Succeeded     bool                   `protobuf:"varint,2,opt,name=succeeded,proto3" json:"succeeded,omitempty"`
	ErrorCode     string                 `protobuf:"bytes,3,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResult) Reset() {
	*x = CommandResult{}
	mi := &file_orbit_plugin_v1_process_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResult) ProtoMessage() {}

func (x *CommandResult) ProtoReflect() protoreflect.Message {
	mi := &file_orbit_plugin_v1_process_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResult.ProtoReflect.Descriptor instead.
func (*CommandResult) Descriptor() ([]byte, []int) {
	return file_orbit_plugin_v1_process_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *CommandResult) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *CommandResult) GetSucceeded() bool {
	if x != nil {
		return x.Succeeded
	}
	return false
}

func (x *CommandResult) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *CommandResult) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type CapabilityResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     uint64                 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Response      *anypb.Any             `protobuf:"bytes,2,opt,name=response,proto3" json:"response,omitempty"`
	ErrorCode     string                 `protobuf:"bytes,3,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapabilityResult) Reset() {
	*x = CapabilityResult{}
	mi := &file_orbit_plugin_v1_process_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilityResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilityResult) ProtoMessage() {}

func (x *CapabilityResult) ProtoReflect() protoreflect.Message {
	mi := &file_orbit_plugin_v1_process_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilityResult.ProtoReflect.Descriptor instead.
func (*CapabilityResult) Descriptor() ([]byte, []int) {
	return file_orbit_plugin_v1_process_plugin_proto_rawDescGZIP(), []int{4}
}

func (x *CapabilityResult) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *CapabilityResult) GetResponse() *anypb.Any {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *CapabilityResult) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

type PluginHealth struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     uint64                 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Status        PluginHealth_Status    `protobuf:"varint,2,opt,name=status,proto3,enum=orbit.plugin.v1.PluginHealth_Status" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginHealth) Reset() {
	*x = PluginHealth{}
	mi := &file_orbit_plugin_v1_process_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginHealth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginHealth) ProtoMessage() {}

func (x *PluginHealth) ProtoReflect() protoreflect.Message {
	mi := &file_orbit_plugin_v1_process_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginHealth.ProtoReflect.Descriptor instead.
func (*PluginHealth) Descriptor() ([]byte, []int) {
	return file_orbit_plugin_v1_process_plugin_proto_rawDescGZIP(), []int{5}
}

func (x *PluginHealth) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *PluginHealth) GetStatus() PluginHealth_Status {
	if x != nil {
		return x.Status
	}
	return PluginHealth_STATUS_UNSPECIFIED
}

func (x *PluginHealth) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CoreFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*CoreFrame_Command
	//	*CoreFrame_HealthProbe
	//	*CoreFrame_Shutdown
	//	*CoreFrame_CapabilityCall
	Payload       isCoreFrame_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoreFrame) Reset() {
	*x = CoreFrame{}
	mi := &file_orbit_plugin_v1_process_plugin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoreFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoreFrame) ProtoMessage() {}

func (x *CoreFrame) ProtoReflect() protoreflect.Message {
	mi := &file_orbit_plugin_v1_process_plugin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoreFrame.ProtoReflect.Descriptor instead.
func (*CoreFrame) Descriptor() ([]byte, []int) {
	return file_orbit_plugin_v1_process_plugin_proto_rawDescGZIP(), []int{6}
}

func (x *CoreFrame) GetPayload() isCoreFrame_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *CoreFrame) GetCommand() *PluginCommand {
	if x != nil {
		if x, ok := x.Payload.(*CoreFrame_Command); ok {
			return x.Command
		}
	}
	return nil
}

func (x *CoreFrame) GetHealthProbe() *HealthProbe {
	if x != nil {
		if x, ok := x.Payload.(*CoreFrame_HealthProbe); ok {
			return x.HealthProbe
		}
	}
	return nil
}

func (x *CoreFrame) GetShutdown() *Shutdown {
	if x != nil {
		if x, ok := x.Payload.(*CoreFrame_Shutdown); ok {
			return x.Shutdown
		}
	}
	return nil
}

func (x *CoreFrame) GetCapabilityCall() *CapabilityCall {
	if x != nil {
		if x, ok := x.Payload.(*CoreFrame_CapabilityCall); ok {
			return x.CapabilityCall
		}
	}
	return nil
}

type isCoreFrame_Payload interface {
	isCoreFrame_Payload()
}

type CoreFrame_Command struct {
	Command *PluginCommand `protobuf:"bytes,1,opt,name=command,proto3,oneof"`
}

type CoreFrame_HealthProbe struct {
	HealthProbe *HealthProbe `protobuf:"bytes,2,opt,name=health_probe,json=healthProbe,proto3,oneof"`
}

type CoreFrame_Shutdown struct {
	Shutdown *Shutdown `protobuf:"bytes,3,opt,name=shutdown,proto3,oneof"`
}

type CoreFrame_CapabilityCall struct {
	CapabilityCall *CapabilityCall `protobuf:"bytes,4,opt,name=capability_call,json=capabilityCall,proto3,oneof"`
}

func (*CoreFrame_Command) isCoreFrame_Payload() {}

func (*CoreFrame_HealthProbe) isCoreFrame_Payload() {}

func (*CoreFrame_Shutdown) isCoreFrame_Payload() {}

func (*CoreFrame_CapabilityCall) isCoreFrame_Payload() {}

type PluginCommand struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	RequestId         uint64                 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Kind              PluginCommand_Kind     `protobuf:"varint,2,opt,name=kind,proto3,enum=orbit.plugin.v1.PluginCommand_Kind" json:"kind,omitempty"`
	ConfigurationJson []byte                 `protobuf:"bytes,3,opt,name=configuration_json,json=configurationJson,proto3" json:"configuration_json,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PluginCommand) Reset() {
	*x = PluginCommand{}
	mi := &file_orbit_plugin_v1_process_plugin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginCommand) ProtoMessage() {}

func (x *PluginCommand) ProtoReflect() protoreflect.Message {
	mi := &file_orbit_plugin_v1_process_plugin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginCommand.ProtoReflect.Descriptor instead.
func (*PluginCommand) Descriptor() ([]byte, []int) {
	return file_orbit_plugin_v1_process_plugin_proto_rawDescGZIP(), []int{7}
}

func (x *PluginCommand) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *PluginCommand) GetKind() PluginCommand_Kind {
	if x != nil {
		return x.Kind
	}
	return PluginCommand_KIND_UNSPECIFIED
}

func (x *PluginCommand) GetConfigurationJson() []byte {
	if x != nil {
		return x.ConfigurationJson
	}
	return nil
}

type HealthProbe struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     uint64                 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthProbe) Reset() {
	*x = HealthProbe{}
	mi := &file_orbit_plugin_v1_process_plugin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthProbe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthProbe) ProtoMessage() {}

func (x *HealthProbe) ProtoReflect() protoreflect.Message {
	mi := &file_orbit_plugin_v1_process_plugin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthProbe.ProtoReflect.Descriptor instead.
func (*HealthProbe) Descriptor() ([]byte, []int) {
	return file_orbit_plugin_v1_process_plugin_proto_rawDescGZIP(), []int{8}
}

func (x *HealthProbe) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

// Capability packages publish their typed request/response messages in their own repositories.
type CapabilityCall struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     uint64                 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Method        string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Request       *anypb.Any             `protobuf:"bytes,3,opt,name=request,proto3" json:"request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapabilityCall) Reset() {
	*x = CapabilityCall{}
	mi := &file_orbit_plugin_v1_process_plugin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilityCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilityCall) ProtoMessage() {}

func (x *CapabilityCall) ProtoReflect() protoreflect.Message {
	mi := &file_orbit_plugin_v1_process_plugin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilityCall.ProtoReflect.Descriptor instead.
func (*CapabilityCall) Descriptor() ([]byte, []int) {
	return file_orbit_plugin_v1_process_plugin_proto_rawDescGZIP(), []int{9}
}

func (x *CapabilityCall) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *CapabilityCall) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *CapabilityCall) GetRequest() *anypb.Any {
	if x != nil {
		return x.Request
	}
	return nil
}

type Shutdown struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Shutdown) Reset() {
	*x = Shutdown{}
	mi := &file_orbit_plugin_v1_process_plugin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Shutdown) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Shutdown) ProtoMessage() {}

func (x *Shutdown) ProtoReflect() protoreflect.Message {
	mi := &file_orbit_plugin_v1_process_plugin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Shutdown.ProtoReflect.Descriptor instead.
func (*Shutdown) Descriptor() ([]byte, []int) {
	return file_orbit_plugin_v1_process_plugin_proto_rawDescGZIP(), []int{10}
}

var File_orbit_plugin_v1_process_plugin_proto protoreflect.FileDescriptor

const file_orbit_plugin_v1_process_plugin_proto_rawDesc = "" +
	"\n" +
	"$orbit/plugin/v1/process_plugin.proto\x12\x0forbit.plugin.v1\x1a\x19google/protobuf/any.proto\"\xa1\x02\n" +
	"\x0ePluginMetadata\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x1f\n" +
	"\vapi_version\x18\x04 \x01(\tR\n" +
	"apiVersion\x12\"\n" +
	"\fdependencies\x18\x05 \x03(\tR\fdependencies\x123\n" +
	"\x15optional_dependencies\x18\x06 \x03(\tR\x14optionalDependencies\x12\"\n" +
	"\fcapabilities\x18\a \x03(\tR\fcapabilities\x123\n" +
	"\x15required_capabilities\x18\b \x03(\tR\x14requiredCapabilities\"\xa2\x02\n" +
	"\vPluginFrame\x124\n" +
	"\x05hello\x18\x01 \x01(\v2\x1c.orbit.plugin.v1.PluginHelloH\x00R\x05hello\x12G\n" +
	"\x0ecommand_result\x18\x02 \x01(\v2\x1e.orbit.plugin.v1.CommandResultH\x00R\rcommandResult\x127\n" +
	"\x06health\x18\x03 \x01(\v2\x1d.orbit.plugin.v1.PluginHealthH\x00R\x06health\x12P\n" +
	"\x11capability_result\x18\x04 \x01(\v2!.orbit.plugin.v1.CapabilityResultH\x00R\x10capabilityResultB\t\n" +
	"\apayload\"\x98\x01\n" +
	"\vPluginHello\x12%\n" +
	"\x0eprotocol_major\x18\x01 \x01(\rR\rprotocolMajor\x12%\n" +
	"\x0eprotocol_minor\x18\x02 \x01(\rR\rprotocolMinor\x12;\n" +
	"\bmetadata\x18\x03 \x01(\v2\x1f.orbit.plugin.v1.PluginMetadataR\bmetadata\"\x90\x01\n" +
	"\rCommandResult\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\x04R\trequestId\x12\x1c\n" +
	"\tsucceeded\x18\x02 \x01(\bR\tsucceeded\x12\x1d\n" +
	"\n" +
	"error_code\x18\x03 \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\"\x82\x01\n" +
	"\x10CapabilityResult\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\x04R\trequestId\x120\n" +
	"\bresponse\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\bresponse\x12\x1d\n" +
	"\n" +
	"error_code\x18\x03 \x01(\tR\terrorCode\"\xe6\x01\n" +
	"\fPluginHealth\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\x04R\trequestId\x12<\n" +
	"\x06status\x18\x02 \x01(\x0e2$.orbit.plugin.v1.PluginHealth.StatusR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"_\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eSTATUS_HEALTHY\x10\x01\x12\x13\n" +
	"\x0fSTATUS_DEGRADED\x10\x02\x12\x14\n" +
	"\x10STATUS_UNHEALTHY\x10\x03\"\x9a\x02\n" +
	"\tCoreFrame\x12:\n" +
	"\acommand\x18\x01 \x01(\v2\x1e.orbit.plugin.v1.PluginCommandH\x00R\acommand\x12A\n" +
	"\fhealth_probe\x18\x02 \x01(\v2\x1c.orbit.plugin.v1.HealthProbeH\x00R\vhealthProbe\x127\n" +
	"\bshutdown\x18\x03 \x01(\v2\x19.orbit.plugin.v1.ShutdownH\x00R\bshutdown\x12J\n" +
	"\x0fcapability_call\x18\x04 \x01(\v2\x1f.orbit.plugin.v1.CapabilityCallH\x00R\x0ecapabilityCallB\t\n" +
	"\apayload\"\xdc\x01\n" +
	"\rPluginCommand\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\x04R\trequestId\x127\n" +
	"\x04kind\x18\x02 \x01(\x0e2#.orbit.plugin.v1.PluginCommand.KindR\x04kind\x12-\n" +
	"\x12configuration_json\x18\x03 \x01(\fR\x11configurationJson\"D\n" +
	"\x04Kind\x12\x14\n" +
	"\x10KIND_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rKIND_ACTIVATE\x10\x01\x12\x13\n" +
	"\x0fKIND_DEACTIVATE\x10\x02\",\n" +
	"\vHealthProbe\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\x04R\trequestId\"w\n" +
	"\x0eCapabilityCall\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\x04R\trequestId\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12.\n" +
	"\arequest\x18\x03 \x01(\v2\x14.google.protobuf.AnyR\arequest\"\n" +
	"\n" +
	"\bShutdown2X\n" +
	"\rProcessPlugin\x12G\n" +
	"\aConnect\x12\x1c.orbit.plugin.v1.PluginFrame\x1a\x1a.orbit.plugin.v1.CoreFrame(\x010\x01BAZ?github.com/orbit-projects/orbit-kubernetes-go/internal/wire;wireb\x06proto3"

var (
	file_orbit_plugin_v1_process_plugin_proto_rawDescOnce sync.Once
	file_orbit_plugin_v1_process_plugin_proto_rawDescData []byte
)

func file_orbit_plugin_v1_process_plugin_proto_rawDescGZIP() []byte {
	file_orbit_plugin_v1_process_plugin_proto_rawDescOnce.Do(func() {
		file_orbit_plugin_v1_process_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_orbit_plugin_v1_process_plugin_proto_rawDesc), len(file_orbit_plugin_v1_process_plugin_proto_rawDesc)))
	})
	return file_orbit_plugin_v1_process_plugin_proto_rawDescData
}

var file_orbit_plugin_v1_process_plugin_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_orbit_plugin_v1_process_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_orbit_plugin_v1_process_plugin_proto_goTypes = []any{
	(PluginHealth_Status)(0), // 0: orbit.plugin.v1.PluginHealth.Status
	(PluginCommand_Kind)(0),  // 1: orbit.plugin.v1.PluginCommand.Kind
	(*PluginMetadata)(nil),   // 2: orbit.plugin.v1.PluginMetadata
	(*PluginFrame)(nil),      // 3: orbit.plugin.v1.PluginFrame
	(*PluginHello)(nil),      // 4: orbit.plugin.v1.PluginHello
	(*CommandResult)(nil),    // 5: orbit.plugin.v1.CommandResult
	(*CapabilityResult)(nil), // 6: orbit.plugin.v1.CapabilityResult
	(*PluginHealth)(nil),     // 7: orbit.plugin.v1.PluginHealth
	(*CoreFrame)(nil),        // 8: orbit.plugin.v1.CoreFrame
	(*PluginCommand)(nil),    // 9: orbit.plugin.v1.PluginCommand
	(*HealthProbe)(nil),      // 10: orbit.plugin.v1.HealthProbe
	(*CapabilityCall)(nil),   // 11: orbit.plugin.v1.CapabilityCall
	(*Shutdown)(nil),         // 12: orbit.plugin.v1.Shutdown
	(*anypb.Any)(nil),        // 13: google.protobuf.Any
}
var file_orbit_plugin_v1_process_plugin_proto_depIdxs = []int32{
	4,  // 0: orbit.plugin.v1.PluginFrame.hello:type_name -> orbit.plugin.v1.PluginHello
	5,  // 1: orbit.plugin.v1.PluginFrame.command_result:type_name -> orbit.plugin.v1.CommandResult
	7,  // 2: orbit.plugin.v1.PluginFrame.health:type_name -> orbit.plugin.v1.PluginHealth
	6,  // 3: orbit.plugin.v1.PluginFrame.capability_result:type_name -> orbit.plugin.v1.CapabilityResult
	2,  // 4: orbit.plugin.v1.PluginHello.metadata:type_name -> orbit.plugin.v1.PluginMetadata
	13, // 5: orbit.plugin.v1.CapabilityResult.response:type_name -> google.protobuf.Any
	0,  // 6: orbit.plugin.v1.PluginHealth.status:type_name -> orbit.plugin.v1.PluginHealth.Status
	9,  // 7: orbit.plugin.v1.CoreFrame.command:type_name -> orbit.plugin.v1.PluginCommand
	10, // 8: orbit.plugin.v1.CoreFrame.health_probe:type_name -> orbit.plugin.v1.HealthProbe
	12, // 9: orbit.plugin.v1.CoreFrame.shutdown:type_name -> orbit.plugin.v1.Shutdown
	11, // 10: orbit.plugin.v1.CoreFrame.capability_call:type_name -> orbit.plugin.v1.CapabilityCall
	1,  // 11: orbit.plugin.v1.PluginCommand.kind:type_name -> orbit.plugin.v1.PluginCommand.Kind
	13, // 12: orbit.plugin.v1.CapabilityCall.request:type_name -> google.protobuf.Any
	3,  // 13: orbit.plugin.v1.ProcessPlugin.Connect:input_type -> orbit.plugin.v1.PluginFrame
	8,  // 14: orbit.plugin.v1.ProcessPlugin.Connect:output_type -> orbit.plugin.v1.CoreFrame
	14, // [14:15] is the sub-list for method output_type
	13, // [13:14] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_orbit_plugin_v1_process_plugin_proto_init() }
func file_orbit_plugin_v1_process_plugin_proto_init() {
	if File_orbit_plugin_v1_process_plugin_proto != nil {
		return
	}
	file_orbit_plugin_v1_process_plugin_proto_msgTypes[1].OneofWrappers = []any{
		(*PluginFrame_Hello)(nil),
		(*PluginFrame_CommandResult)(nil),
		(*PluginFrame_Health)(nil),
		(*PluginFrame_CapabilityResult)(nil),
	}
	file_orbit_plugin_v1_process_plugin_proto_msgTypes[6].OneofWrappers = []any{
		(*CoreFrame_Command)(nil),
		(*CoreFrame_HealthProbe)(nil),
		(*CoreFrame_Shutdown)(nil),
		(*CoreFrame_CapabilityCall)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_orbit_plugin_v1_process_plugin_proto_rawDesc), len(file_orbit_plugin_v1_process_plugin_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_orbit_plugin_v1_process_plugin_proto_goTypes,
		DependencyIndexes: file_orbit_plugin_v1_process_plugin_proto_depIdxs,
		EnumInfos:         file_orbit_plugin_v1_process_plugin_proto_enumTypes,
		MessageInfos:      file_orbit_plugin_v1_process_plugin_proto_msgTypes,
	}.Build()
	File_orbit_plugin_v1_process_plugin_proto = out.File
	file_orbit_plugin_v1_process_plugin_proto_goTypes = nil
	file_orbit_plugin_v1_process_plugin_proto_depIdxs = nil
}
